apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-app-vm
spec:
  replicas: 3 # High Availability & Load Balancing
  selector:
    matchLabels:
      app: ci-cd-app-vm
  template:
    metadata:
      labels:
        app: ci-cd-app-vm
    spec:
      containers:
        - name: ci-cd-app-vm
          image: DOCKER_IMAGE_TAG # Replaced dynamically by CI/CD pipeline
          ports:
            - containerPort: 8080