apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app-vm-service
spec:
  selector:
    app: ci-cd-app-vm
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080