apiVersion: v1
kind: Service
metadata:
  name: student-vm-service
spec:
  selector:
    app: student-vm
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 8090